# Generated by Django 3.0.5 on 2020-04-25 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clienti',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('CNP_Client', models.CharField(max_length=14)),
                ('nume', models.CharField(max_length=35)),
                ('prenume', models.CharField(max_length=35)),
                ('adresa', models.TextField()),
                ('telefon', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'Clienti',
            },
        ),
        migrations.CreateModel(
            name='Comenzi',
            fields=[
                ('id_comanda', models.AutoField(primary_key=True, serialize=False)),
                ('data_comanda', models.DateField()),
                ('stare_comanda', models.CharField(max_length=35)),
                ('descriere', models.TextField(blank=True, null=True)),
                ('CNP_Client', models.ForeignKey(db_column='CNP_Client', on_delete=django.db.models.deletion.DO_NOTHING, to='web_interface.Clienti')),
            ],
            options={
                'db_table': 'Comenzi',
            },
        ),
        migrations.CreateModel(
            name='Constatari',
            fields=[
                ('id_constatare', models.AutoField(primary_key=True, serialize=False)),
                ('pret_lucrare', models.IntegerField()),
                ('id_comanda', models.OneToOneField(db_column='id_comanda', on_delete=django.db.models.deletion.DO_NOTHING, to='web_interface.Comenzi')),
            ],
            options={
                'db_table': 'Constatari',
            },
        ),
        migrations.CreateModel(
            name='Echipe',
            fields=[
                ('id_echipa', models.AutoField(primary_key=True, serialize=False)),
                ('nume_echipa', models.CharField(db_column='nume_echipa', max_length=25)),
            ],
            options={
                'db_table': 'Echipe',
            },
        ),
        migrations.CreateModel(
            name='Specialisti',
            fields=[
                ('id_specialist', models.AutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=35)),
                ('prenume', models.CharField(max_length=35)),
                ('specializare', models.CharField(max_length=25)),
                ('nume_echipa', models.ForeignKey(db_column='nume_echipa', on_delete=django.db.models.deletion.DO_NOTHING, to='web_interface.Echipe')),
            ],
            options={
                'db_table': 'Specialisti',
            },
        ),
        migrations.CreateModel(
            name='Sarcini',
            fields=[
                ('id_sarcina', models.AutoField(primary_key=True, serialize=False)),
                ('task', models.TextField(db_column='Task')),
                ('id_constatare', models.ForeignKey(db_column='id_constatare', on_delete=django.db.models.deletion.DO_NOTHING, to='web_interface.Constatari')),
            ],
            options={
                'db_table': 'Sarcini',
            },
        ),
        migrations.CreateModel(
            name='Piese',
            fields=[
                ('id_piesa', models.AutoField(primary_key=True, serialize=False)),
                ('pret', models.IntegerField()),
                ('cantitate', models.IntegerField()),
                ('nume_piesa', models.CharField(max_length=55)),
                ('id_constatare', models.ForeignKey(db_column='id_constatare', on_delete=django.db.models.deletion.DO_NOTHING, to='web_interface.Constatari')),
            ],
            options={
                'db_table': 'Piese',
            },
        ),
        migrations.AddField(
            model_name='constatari',
            name='id_echipa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web_interface.Echipe'),
        ),
    ]
